services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    env_file:
      - .env
    container_name: homepage
    network_mode: host
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "192.168.50.50:3000,cosmokramer.lan:3000,homepage.vamshi.ca"
    restart: unless-stopped
    labels:
      - "wud.trigger.include=homepage"
