services:
  whatsupdocker:
    image: getwud/wud
    container_name: wud
    environment:
      - WUD_AUTH_ADMIN_USER=cosmo
      - WUD_AUTH_ADMIN_PASSWORD=${WUD_PASSWORD}
      - WUD_TRIGGER_DISCORD_LOCAL_URL=${WUD_TRIGGER_DISCORD_LOCAL_URL}
      - WUD_TRIGGER_DISCORD_LOCAL_BOTUSERNAME=${WUD_TRIGGER_DISCORD_LOCAL_BOTUSERNAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3003:3000
