services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    network_mode: host
    volumes:
      - './data/adguard-home/work:/opt/adguardhome/work'
      - './data/adguard-home/confdir:/opt/adguardhome/conf'

