services:
  glances:
    image: nicolargo/glances:3.4.0.5
    container_name: glances
    restart: unless-stopped
    pid: host
    network_mode: host
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/etc/os-release:ro
      - /:/host:ro
      - /:/rootfs:ro
    environment:
      - GLANCES_OPT=-w --fs

