---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- MichaelScott:

    - Home Assistant:
        icon: home-assistant.svg
        href: "http://{{HOMEPAGE_VAR_MICHAEL_SCOTT}}:8123"
        widget:
          type: homeassistant
          url: "http://{{HOMEPAGE_VAR_MICHAEL_SCOTT}}:8123"
          key: "{{HOMEPAGE_VAR_HOME_ASSISTANT_TOKEN}}"
          fields: ["people_home", "lights_on", "switches_on"]


- CosmoKramer:
    - Pi-hole:
        icon: pi-hole.png
        href: "http://{{HOMEPAGE_VAR_COSMO_KRAMER}}/admin/"
        description: Network-wide ad blocker
        widget:
          type: pihole
          url: "http://{{HOMEPAGE_VAR_COSMO_KRAMER}}"
          key: "{{HOMEPAGE_VAR_PIHOLE_TOKEN}}"
          version: 6
          fields:
            - queries
            - blocked
            - blocked_percent
            - gravity
            - unique_clients
