---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/
- resources:
    cpu: true
    memory: true
    disk: /
    cputemp: true
    tempmin: 0 # optional, minimum cpu temp
    tempmax: 100 # optional, maximum cpu temp
    uptime: true
    units: metric # only used by cpu temp, options: 'imperial' or 'metric'
      #refresh: 3000 # optional, in ms
      #diskUnits: bytes # optional, bytes (default) or bbytes. Only applies to disk
    network: true # optional, uses 'default' if true or specify a network interface name

- openmeteo:
    label: Nepean
    latitude: 45.3362
    longitude: -75.7225
    timezone: America/Toronto
    units: metric
    cache: 5
