---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- openmeteo:
    label: Nepean
    latitude: 45.3362
    longitude: -75.7225
    timezone: America/Toronto
    units: metric
    cache: 5

- glances:
    # label: scott
    url: "http://{{HOMEPAGE_VAR_COSMO_KRAMER}}:61208"
    version: 3
    cpu: true
    cputemp: true
    mem: true
    disk: /rootfs
    uptime: true
      #network: true
      #expanded: true
